<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Maxine.Extensions\Maxine.Extensions\Maxine.Extensions.csproj" />
      <ProjectReference Include="..\WorldXaml.Core\WorldXaml.Core.csproj" />
      <ProjectReference Include="..\XamlX\src\XamlX\XamlX.csproj" />
    </ItemGroup>

</Project>
