using System;
using System.Collections.Generic;
using Avalonia.Generators.Common.Domain;

namespace Avalonia.Generators.NameGenerator;

internal class XamlXCodeGenerator(
    bool avaloniaNameGeneratorAttachDevTools,
    NamedFieldModifier defaultNamedFieldModifier = NamedFieldModifier.Internal,
    string? compiledXamlSource = null) : ICodeGenerator
{
    private string _generatorName = typeof(XamlXCodeGenerator).FullName;
    private string _generatorVersion = typeof(XamlXCodeGenerator).Assembly.GetName().Version.ToString();

    private const string AttachDevToolsCodeBlock =
        """
        #if DEBUG
                    if (attachDevTools)
                    {
                        this.AttachDevTools();
                    }
        #endif

        """;

    private const string AttachDevToolsParameterDocumentation
        = """
                  /// <param name="attachDevTools">Should the dev tools be attached.</param>

          """;


    public string GenerateCode(string className, string nameSpace, IEnumerable<ResolvedName> names)
    {
        var properties = new List<string>();
        var initializations = new List<string>();
        const string thisFindNameScopeVariable = "            var __thisNameScope__ = this.FindNameScope();";
        bool hasNames = false;

        foreach (var resolvedName in names)
        {
            if (!hasNames)
            {
                initializations.Add(thisFindNameScopeVariable);
            }

            var (typeName, name, fieldModifier) = resolvedName;
            var propertySource =
                $"""
                         [global::System.CodeDom.Compiler.GeneratedCode("{_generatorName}", "{_generatorVersion}")]
                         {fieldModifier ?? defaultNamedFieldModifier.ToString().ToLowerInvariant()} {typeName} {name};
                 """;
            properties.Add(propertySource);
            initializations.Add($"            {name} = __thisNameScope__?.Find<{typeName}>(\"{name}\");");

            hasNames = true;
        }

        var attachDevTools = avaloniaNameGeneratorAttachDevTools;
        var hasCompiledXaml = !string.IsNullOrEmpty(compiledXamlSource);

        var loadXamlBody = hasCompiledXaml
            ? $"                global::Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(this);"
            : "                AvaloniaXamlLoader.Load(this);";

        // When compiled XAML is present, add explicit ICompiledView<T> implementation
        // that delegates to the XamlX-generated Populate/Build (which use the base type).
        var interfaceImpl = hasCompiledXaml
            ? $$"""

                        static void global::Avalonia.Markup.Xaml.ICompiledView<{{className}}>.Populate(global::System.IServiceProvider? serviceProvider, {{className}} instance)
                            => Populate(serviceProvider, instance);

                        static {{className}} global::Avalonia.Markup.Xaml.ICompiledView<{{className}}>.Build(global::System.IServiceProvider? serviceProvider)
                            => ({{className}})Build(serviceProvider);
                """
            : string.Empty;

        return $$"""
                 // <auto-generated />

                 using Avalonia;
                 using Avalonia.Controls;
                 using Avalonia.Markup.Xaml;

                 namespace {{nameSpace}}
                 {
                     partial class {{className}}{{(hasCompiledXaml ? $" : global::Avalonia.Markup.Xaml.ICompiledView<{className}>" : string.Empty)}}
                     {
                 {{string.Join("\n", properties)}}

                         /// <summary>
                         /// Wires up the controls and optionally loads XAML markup and attaches dev tools (if Avalonia.Diagnostics package is referenced).
                         /// </summary>
                         /// <param name="loadXaml">Should the XAML be loaded into the component.</param>
                 {{(attachDevTools ? AttachDevToolsParameterDocumentation : string.Empty)}}
                         [global::System.CodeDom.Compiler.GeneratedCode("{{_generatorName}}", "{{_generatorVersion}}")]
                         [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                         public void InitializeComponent(bool loadXaml = true{{(attachDevTools ? ", bool attachDevTools = true" : string.Empty)}})
                         {
                             if (loadXaml)
                             {
                 {{loadXamlBody}}
                             }
                 {{(attachDevTools ? AttachDevToolsCodeBlock : string.Empty)}}
                 {{string.Join("\n", initializations)}}
                         }
                 {{(hasCompiledXaml ? "\n" + compiledXamlSource : string.Empty)}}
                 {{interfaceImpl}}
                     }
                 }

                 """;
    }
}