using System.Windows.Markup;
using Avalonia.Metadata;
using WorldXaml.UI.Base.Xaml;

// ReSharper disable once CheckNamespace
namespace Avalonia.Markup.Xaml;

// Stub so Rider resolves x:DataType as a known directive
public static class XamlDirectives
{
    public static readonly AvaloniaProperty DataType = null!;
}

/// <summary>
/// Provides access to the root object during XAML instantiation.
/// </summary>
public interface IRootObjectProvider
{
    /// <summary>
    /// The root object of the xaml file
    /// </summary>
    object RootObject { get; }
    /// <summary>
    /// The "current" root object, contains either the root of the xaml file
    /// or the root object of the control/data template 
    /// </summary>
    object IntermediateRootObject { get; }
}

/// <summary>
/// Provides URI context during XAML loading.
/// </summary>
public interface IUriContext
{
    /// <summary>
    /// Gets or sets the base URI of the current XAML document.
    /// </summary>
    Uri? BaseUri { get; set; }
}

/// <summary>
/// Provides information about the target of a markup extension.
/// </summary>
public interface IProvideValueTarget
{
    /// <summary>
    /// Gets the target object where a value is being set.
    /// </summary>
    object? TargetObject { get; }

    /// <summary>
    /// Gets the target property where a value is being set.
    /// </summary>
    object? TargetProperty { get; }
}

public interface ICompiledView;

public interface ICompiledView<T> : ICompiledView
{
    public static abstract void Populate(IServiceProvider? serviceProvider, T instance);
    public static abstract T Build(IServiceProvider? serviceProvider);
}

public static class AvaloniaXamlLoader
{
    /// <summary>
    /// Creates a service provider with default services for XAML instantiation.
    /// </summary>
    public static IServiceProvider CreateDefaultServiceProvider(object? rootObject = null, string? baseUri = null)
    {
        var provider = new XamlServiceProvider(
            rootObjectProvider: new RootObjectProviderImpl
            {
                RootObject = rootObject,
                IntermediateRootObject = rootObject
            },
            uriContext: new UriContextImpl
            {
                BaseUri = baseUri != null ? new Uri(baseUri) : null
            },
            provideValueTarget: new ProvideValueTargetImpl()
        );

        return provider;
    }

    /// <summary>
    /// Populates a XAML-based view by calling its generated Populate method.
    /// </summary>
    /// <typeparam name="T">The type of the view (must have a static Populate method generated by XamlX).</typeparam>
    /// <param name="instance">The instance to populate.</param>
    /// <param name="serviceProvider">Optional service provider. If null, a default one is created.</param>
    public static void Load<T>(T instance, IServiceProvider? serviceProvider = null) where T : ICompiledView<T>
    {
        serviceProvider ??= CreateDefaultServiceProvider(instance);

        T.Populate(serviceProvider, instance);
    }

    /// <summary>
    /// Creates and populates a XAML-based view.
    /// </summary>
    /// <typeparam name="T">The type of the view (must have a static Build method generated by XamlX).</typeparam>
    /// <param name="serviceProvider">Optional service provider. If null, a default one is created.</param>
    /// <returns>A new instance of the view with XAML properties applied.</returns>
    public static T Create<T>(IServiceProvider? serviceProvider = null) where T : ICompiledView<T>
    {
        serviceProvider ??= CreateDefaultServiceProvider();

        return T.Build(serviceProvider);
    }
}